

export const journals = [
    {
      title: "A Study on Data Science Trends and Machine Learning Algorithms",
      authors: "John Doe, Jane Smith, Emily White",
      journal: "Journal of Computer Science and Technology",
     
      year: "2023",
      index: "SCI",
      abstract: "This paper explores the latest trends in data science, including emerging machine learning algorithms, and their real-world applications across industries such as healthcare, finance, and technology.",
      keywords: ["Data Science", "Machine Learning", "Artificial Intelligence", "Big Data", "Healthcare"],
      doi: "10.1007/JCS2023.0001234",
    },
    {
      title: "Innovations in Artificial Intelligence: A Comprehensive Review",
      authors: "Alice Brown, Bob White, Michael Green",
      journal: "AI Research Journal",
      volume: "12",
      pages: "45-58",
      year: "2022",
      index: "Scopus",
      abstract: "This article provides an in-depth review of the latest innovations in AI, focusing on deep learning, reinforcement learning, and AI ethics. It also explores future trends in AI applications for automation and decision-making.",
      keywords: ["Artificial Intelligence", "Deep Learning", "Reinforcement Learning", "AI Ethics", "Automation"],
      doi: "10.1109/AIRes2022.0056738",
    },
    {
      title: "Blockchain Technology in Finance: Challenges and Opportunities",
      authors: "Charlie Green, Lisa Black, James Brown",
      journal: "Finance and Technology Journal",
      volume: "8",
      pages: "78-85",
      year: "2021",
      index: "Web of Science",
      abstract: "This paper investigates the impact of blockchain technology on the finance industry, focusing on the potential benefits of decentralized finance (DeFi), the challenges of regulatory compliance, and the future of smart contracts.",
      keywords: ["Blockchain", "Decentralized Finance", "Finance", "Smart Contracts", "Regulatory Compliance"],
      doi: "10.1109/FinTech2021.0078891",
    },
    {
      title: "Quantum Computing and Its Application in Cryptography",
      authors: "Sarah White, Robert Black, David Green",
      journal: "International Journal of Quantum Computing",
      volume: "5",
      pages: "12-22",
      year: "2020",
      index: "IEEE Xplore",
      abstract: "This paper explores the potential applications of quantum computing in cryptography, including quantum key distribution and the risks posed by quantum computing to traditional encryption methods.",
      keywords: ["Quantum Computing", "Cryptography", "Quantum Key Distribution", "Encryption", "Cybersecurity"],
      doi: "10.1109/IJQC2020.0098765",
    },
    {
      title: "The Future of 5G Networks and Internet of Things (IoT)",
      authors: "Michael Grey, Patricia Blue, Angela Brown",
      journal: "Telecommunications and Networking Journal",
      volume: "15",
      pages: "1-10",
      year: "2023",
      index: "EI Compendex",
      abstract: "This paper discusses the impact of 5G networks on the expansion of IoT technologies, highlighting challenges in connectivity, network architecture, and security considerations for widespread IoT adoption.",
      keywords: ["5G", "IoT", "Telecommunications", "Network Architecture", "Security"],
      doi: "10.1109/TNCJ2023.0054321",
    },
  ];




  export  const conferences = [
    {
      title: "Feature Extraction and Classification Based on Pixel in Banana Fruit for Disease Detection Using Neural Networks",
      authors: "Mahendran, T., Seetharaman, K., Ramakrishnan, S.",
      conference: "Third International Conference on Advances in Electrical, Computing, Communication and Sustainable Technologies (ICAECT)",
      location: "IEEE Xplore, Online Conference",
      year: 2023,
      pages: "1-7",
      doi: "10.1109/ICAECT57570.2023.10117959",
      abstract: "This paper presents an advanced method for feature extraction and classification based on pixel analysis in banana fruit images. The study employs neural networks to detect diseases such as black Sigatoka and Panama wilt in banana plants, contributing to better agricultural practices.",
      keywords: ["Feature Extraction", "Machine Learning", "Neural Networks", "Agriculture", "Disease Detection"],
      proceedings: "Proceedings of ICAECT 2023",
      organizer: "IEEE, Department of Electrical Engineering",
      link: "https://ieeexplore.ieee.org/document/10117959",
    },
    {
      title: "AI in Healthcare: Transforming Patient Care and Medical Research",
      authors: "Dr. A, Dr. B, Dr. C",
      conference: "International AI Conference on Healthcare Technologies",
      location: "London, UK",
      year: 2021,
      pages: "35-45",
      doi: "10.1109/AIHC2021.3456789",
      abstract: "This paper explores the role of artificial intelligence in revolutionizing the healthcare sector, particularly in diagnostics, patient care, and medical research. It covers the integration of AI tools like machine learning, natural language processing, and computer vision in various medical applications.",
      keywords: ["AI in Healthcare", "Medical Research", "Machine Learning", "Diagnostics", "Patient Care"],
      proceedings: "Proceedings of AIHC 2021",
      organizer: "International AI Consortium",
      link: "https://ieeexplore.ieee.org/document/3456789",
    },
    {
      title: "Blockchain for Secure Health Data Sharing: A Decentralized Solution",
      authors: "Samuel Williams, Natasha Green, Jacob Lee",
      conference: "International Conference on Blockchain Technology in Health Systems",
      location: "Berlin, Germany",
      year: 2022,
      pages: "58-67",
      doi: "10.1109/ICBTHS2022.0088763",
      abstract: "This conference paper proposes a blockchain-based solution to securely share medical data across different health systems. The method addresses privacy concerns while enabling interoperability between healthcare providers, using smart contracts and decentralized storage.",
      keywords: ["Blockchain", "Health Data", "Smart Contracts", "Data Privacy", "Health Systems"],
      proceedings: "Proceedings of ICBTHS 2022",
      organizer: "Global Blockchain Technology Network",
      link: "https://ieeexplore.ieee.org/document/0088763",
    },
    {
      title: "5G Technologies in Smart Cities: Connecting the Future",
      authors: "Eleanor Brooks, Thomas Lee, Daniel Williams",
      conference: "International Conference on Next-Gen 5G Networks and Smart Cities",
      location: "New York, USA",
      year: 2023,
      pages: "45-53",
      doi: "10.1109/5GSmartCities2023.0085642",
      abstract: "This paper investigates the impact of 5G technologies on the development of smart cities. It focuses on how 5G networks can enhance connectivity, enable real-time monitoring, improve urban mobility, and foster sustainability in cities.",
      keywords: ["5G", "Smart Cities", "IoT", "Urban Mobility", "Sustainability"],
      proceedings: "Proceedings of 5GSmartCities 2023",
      organizer: "IEEE Smart Cities Initiative",
      link: "https://ieeexplore.ieee.org/document/0085642",
    },
    {
      title: "Quantum Computing and Its Potential to Revolutionize Cryptography",
      authors: "Grace Wilson, Samuel Newton, Oliver Park",
      conference: "International Quantum Computing Symposium",
      location: "San Francisco, USA",
      year: 2020,
      pages: "122-130",
      doi: "10.1109/QuantumCrypt2020.0098765",
      abstract: "This paper discusses the groundbreaking potential of quantum computing in the field of cryptography, including quantum key distribution, post-quantum cryptography algorithms, and the implications of quantum supremacy on traditional encryption methods.",
      keywords: ["Quantum Computing", "Cryptography", "Quantum Key Distribution", "Post-Quantum", "Encryption"],
      proceedings: "Proceedings of QuantumCrypt 2020",
      organizer: "Institute for Quantum Technologies",
      link: "https://ieeexplore.ieee.org/document/0098765",
    },
  ];



  export const patents = [
    {
      title: "A Method of Retrieving Satellite Image for Remote Sensing Applications",
      applicationNumber: "202241031679",
      grantNumber: "418134",
      dateGranted: "16/01/2023",
      patentee: "Annamalai University",
      abstract: "This invention provides a method for efficiently retrieving satellite images for remote sensing applications, with improved resolution and accuracy using neural network-based algorithms.",
      keywords: ["Satellite Imaging", "Remote Sensing", "Neural Networks", "Data Retrieval"],
      assignee: "Annamalai University Department of Geospatial Sciences",
      internationalApplication: "PCT/IN2023/123456",
    },
    {
      title: "Method for Improved Water Purification Using Advanced Filtration Technology",
      applicationNumber: "202241045783",
      grantNumber: "418589",
      dateGranted: "02/04/2023",
      patentee: "University of Delhi",
      abstract: "A new filtration technology that uses an innovative composite material to improve the purification of water by removing heavy metals and pathogens, making water safer for drinking and industrial use.",
      keywords: ["Water Purification", "Filtration Technology", "Heavy Metal Removal", "Water Safety"],
      assignee: "University of Delhi Department of Environmental Engineering",
      internationalApplication: "PCT/IN2023/654321",
    },
    {
      title: "Innovative Biodegradable Plastic Packaging for Sustainable Development",
      applicationNumber: "202241079234",
      grantNumber: "418788",
      dateGranted: "25/05/2023",
      patentee: "Indian Institute of Technology, Madras",
      abstract: "This patent proposes a biodegradable plastic material made from natural polymers that offers a more sustainable alternative to traditional plastic, reducing environmental pollution and promoting sustainable packaging.",
      keywords: ["Biodegradable Plastic", "Sustainability", "Environmental Impact", "Green Packaging"],
      assignee: "Indian Institute of Technology, Madras, Department of Materials Science",
      internationalApplication: "PCT/IN2023/789654",
    },
    {
      title: "Artificial Intelligence System for Predictive Healthcare Diagnosis",
      applicationNumber: "202241087653",
      grantNumber: "418999",
      dateGranted: "10/06/2023",
      patentee: "Manipal University",
      abstract: "This invention relates to a healthcare system using artificial intelligence for the early detection and prediction of various diseases based on patient data analysis, improving diagnosis efficiency and patient care.",
      keywords: ["Artificial Intelligence", "Healthcare", "Predictive Diagnosis", "Medical Technology"],
      assignee: "Manipal University Department of Healthcare Technology",
      internationalApplication: "PCT/IN2023/654987",
    },
    {
      title: "Efficient Energy Storage and Conversion System for Solar Power Applications",
      applicationNumber: "202241099876",
      grantNumber: "419111",
      dateGranted: "15/07/2023",
      patentee: "National Institute of Technology, Karnataka",
      abstract: "An energy storage and conversion system designed to optimize the efficiency of solar power generation and distribution, providing better energy storage solutions for grid integration and reducing energy wastage.",
      keywords: ["Energy Storage", "Solar Power", "Energy Conversion", "Sustainable Energy"],
      assignee: "National Institute of Technology, Karnataka, Department of Renewable Energy",
      internationalApplication: "PCT/IN2023/321654",
    },
  ];